# Example: Using commando-standard library from git
#
# This demonstrates loading modules from a git repository
# installed to commando home (~/.commando/node_modules/)

dependencies:
  # Use git+ssh:// for SSH authentication (works with private repos)
  - git+ssh://git@github.com/jdillon/commando-standard.git#module-system

modules:
  # Load the hello module from commando-standard
  # Package name comes from commando-standard/package.json: "@planet57/commando-standard"
  - "@planet57/commando-standard/hello"
